apiVersion: v1
kind: Template
metadata:
  name: thoth-metrics-exporter-imagestream
  annotations:
    description: >
      This is Thoth Metrics Exporter ImageStream, this template is meant to be used by
      Bots, but could also be used by humans...
    openshift.io/display-name: 'Thoth Metrics Exporter ImageStream'
    version: 0.1.0
    tags: thoth,thoth-metrics,thoth-metrics-exporter,ai-stacks,aistacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This is Thoth Metrics Exporter ImageStream, this template is meant to be used
      by Bots, but could also be used by humans...
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: thoth-metrics-exporter-imagestream
    app: thoth
    component: metrics-exporter

parameters:
  - description: Tag of the ImageStream to use
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: 'latest'

objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      labels:
        app: thoth
        component: metrics-exporter
      name: metrics-exporter
    spec:
      name: ${IMAGE_STREAM_TAG}

